Manipulação de dados com Python

## Numpy

Lalala

In [2]:
# -*- coding: utf-8 -*-

# Definindo numpy
import numpy as np

# Criando uma matriz
a = np.random.random_integers(0, 4, (3, 3))
print ("Matriz A\n", a)
b = np.random.random_integers(0, 4, (3, 3))
print ("Matriz B\n" ,b)

# Tomando as dimensões de uma matriz
print ("A matriz A tem a forma", a.shape)
print ("A matriz A tem a forma", b.shape)

# Fazendo cálculos simples (soma, subtração, multiplicação e divisão)
# Soma de matrizes
print("Matriz A+B\n", np.add(a,b))
# Subtração de matrizes
print("Matriz A-B\n", np.subtract(a,b))
# Multiplicação de matrizes
print("Matriz A*B elementwise\n", np.dot(a,b))
# Multiplicação elementwise
print("Matriz A*B\n", np.multiply(a,b))
# Criando uma matriz identidade
print("Matriz Identidade\n", np.identity(3))
# Criando uma matriz de um's
print("Matriz com 1's\n", np.ones((3,3)))

Matriz A
 [[1 1 3]
 [3 4 0]
 [4 0 3]]
Matriz B
 [[1 4 0]
 [0 2 0]
 [1 1 1]]
A matriz A tem a forma (3, 3)
A matriz A tem a forma (3, 3)
Matriz A+B
 [[2 5 3]
 [3 6 0]
 [5 1 4]]
Matriz A-B
 [[ 0 -3  3]
 [ 3  2  0]
 [ 3 -1  2]]
Matriz A*B elementwise
 [[ 4  9  3]
 [ 3 20  0]
 [ 7 19  3]]
Matriz A*B
 [[1 4 0]
 [0 8 0]
 [4 0 3]]
Matriz Identidade
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz com 1's
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/Users/apple/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning: This function is deprecated. Please call randint(0, 4 + 1) instead
  import sys
/Users/apple/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: This function is deprecated. Please call randint(0, 4 + 1) instead
  if __name__ == '__main__':
