Manipulação de dados com Python

## Numpy

In [3]:
import numpy as np

In [5]:
minha_lista = [1,2,3,4,5]

In [10]:
print(minha_lista)

[1, 2, 3, 4, 5]


Criando uma array de uma lista

In [11]:
np.array(minha_lista)

array([1, 2, 3, 4, 5])

Para criar uma array de duas dimensões,

In [15]:
minha_matriz = [[1,2], [3,4], [5,6]]

In [16]:
np.array(minha_matriz)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Criação de uma matriz identidade,

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Linspace - especifica o início, o fim e quantos números você quer ver dentro da série, que está igualmente espaçada

In [26]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [31]:
np.random.rand(2)

array([0.13720386, 0.68148475])

In [32]:
np.random.rand(5,4)

array([[0.49563102, 0.0300431 , 0.56526506, 0.70484241],
       [0.3967452 , 0.35609314, 0.05978039, 0.01904008],
       [0.46125747, 0.12091054, 0.08327948, 0.52317648],
       [0.62389454, 0.21392054, 0.0083124 , 0.12693012],
       [0.40393484, 0.79179255, 0.76064567, 0.00334193]])

Para criar números aleatórios entre dois valores,

In [181]:
np.random.randint(0,9)

3

Para gerar 5 números inteiros aleatórios no range de 0 a 9:

In [186]:
x=[randint(0,9) for p in range(0,5)]
print(x)

[2, 4, 6, 8, 2]


Estes mesmos números aleatórios porém float (entre -0.5 e 1, tamanho 3 elementos):

In [195]:
x=np.random.uniform(low=-0.5, high=1,size=3)
print(x)

[ 0.22849984  0.92917565 -0.41305001]


In [198]:
type(x)

numpy.ndarray

Para arredondar os valores,

In [197]:
np.round(x,2)

array([ 0.23,  0.93, -0.41])

Falando de reshape agora

In [205]:
arr = np.random.rand(16)

In [206]:
arr

array([0.49882701, 0.376835  , 0.24572265, 0.39313071, 0.64880047,
       0.50764171, 0.10705421, 0.36960669, 0.4184304 , 0.86072084,
       0.60304953, 0.83498411, 0.36065766, 0.56842946, 0.09692664,
       0.48296871])

In [207]:
brr = arr.reshape(4,4)

In [208]:
brr

array([[0.49882701, 0.376835  , 0.24572265, 0.39313071],
       [0.64880047, 0.50764171, 0.10705421, 0.36960669],
       [0.4184304 , 0.86072084, 0.60304953, 0.83498411],
       [0.36065766, 0.56842946, 0.09692664, 0.48296871]])

In [212]:
crr = arr.reshape(8,2)

In [213]:
crr

array([[0.49882701, 0.376835  ],
       [0.24572265, 0.39313071],
       [0.64880047, 0.50764171],
       [0.10705421, 0.36960669],
       [0.4184304 , 0.86072084],
       [0.60304953, 0.83498411],
       [0.36065766, 0.56842946],
       [0.09692664, 0.48296871]])

In [216]:
arr.max()

0.8607208384404846

In [217]:
arr.argmax()

9

In [218]:
arr.min()

0.09692664195780054

In [220]:
arr.argmin()

14

## Indexação e fatiamento de arrays

In [223]:
import numpy as np

arr = np.arange(0,30,3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27]


In [227]:
arr[3]

9

Puxando dois elementos,

In [226]:
arr[3:5]

array([ 9, 12])

Não colocando nada, nós temos todos os elementos até lá

In [230]:
arr[:3]

array([0, 3, 6])

In [234]:
arr[4:]

array([10, 10, 10, 10, 10, 10])

Alterando os dados dalí para frente

In [235]:
arr[3:] = 10

In [236]:
arr

array([ 0,  3,  6, 10, 10, 10, 10, 10, 10, 10])

In [237]:
arr = np.arange(50).reshape((5,10))

In [238]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [242]:
arr.shape

(5, 10)

O primeiro índice faz menção às linhas e o segundo às colunas

In [243]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [249]:
arr2 = arr[:3]

In [250]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Um problema:

In [246]:
arr2[:] = 100

In [247]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [248]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Para não alterar os valores da array original,

In [252]:
arr = np.arange(50).reshape((5,10))
arr2 = arr[:3].copy()

In [253]:
arr2[:] = 100

In [254]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [255]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Nice!

Usando a segunda notação, com vírgulas:

In [256]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [257]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [261]:
bol = arr > 25
print(bol)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [262]:
arr[bol]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [264]:
arr[bol].shape

(24,)

xxxxxx

In [6]:
import numpy as np

arr = np.arange(0,16)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Estas operações são element-wise

In [9]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [10]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [11]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr**arr

array([                 1,                  1,                  4,
                       27,                256,               3125,
                    46656,             823543,           16777216,
                387420489,        10000000000,       285311670611,
            8916100448256,    302875106592253,  11112006825558016,
       437893890380859375])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [16]:
np.mean(arr)

7.5

In [18]:
np.std(arr)

4.6097722286464435

In [19]:
np.max(arr)

15

In [20]:
arr.max()

15

O link docs scipy tem uma explicação da biblioteca do numpy e as funções contidas no mesmo. É sempre bom visitar para tirar as dúvidas quando aparecerem